In [2]:
import pandas as pd

df_historico = pd.read_excel('../data/raw/precios_comb_liquidos_en_el_pais-2026-08-03.xlsx')
df_historico.shape

(0, 0)

In [2]:
xls = pd.ExcelFile('../data/raw/precios_comb_liquidos_en_el_pais-2026-08-03.xlsx')
print(xls.sheet_names)

['Hoja1', 'Gasolina 93 sp', 'Gasolina 95 sp', 'Gasolina 97 sp', 'Petróleo Diesel', 'Kerosene Doméstico']

In [3]:
df_93 = pd.read_excel('../data/raw/precios_comb_liquidos_en_el_pais-2026-08-03.xlsx', sheet_name='Gasolina 93 sp')
df_93.shape

(402, 18)

In [4]:
df_93.head(10)

,Unnamed: 0,Unnamed: 1,PRECIOS OBSERVADOS A PÚBLICO: PROMEDIOS NOMINALES EN REGIONES Y REGIÓN METROPOLITANA ($/LITRO),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,FUENTE HASTA DICIEMBRE 2012: ENCUESTA DE PRECI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,FUENTE DESDE ENERO 2013: Corresponde al precio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ND: NO DISPONIBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NE: NO EXISTE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,13,15,1,2,3,4,5,6,7,16,8,9,14,10,11,12
5,NaN,GASOLINA,NaN,NaN,NaN,NaN,NaN,NaN,REGIONES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,93 S/P,REGIÓN,XV REGIÓN,I REGIÓN,II REGIÓN,III REGIÓN,IV REGIÓN,V REGIÓN,VI REGIÓN,VII REGIÓN,XVI REGIÓN,VIII REGIÓN,IX REGIÓN,XIV REGIÓN,X REGIÓN,XI REGIÓN,XII REGIÓN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Fecha,METROPOLITANA,ARICA,IQUIQUE,ANTOFAGASTA,COPIAPÓ,LA SERENA,VALPARAÍSO,RANCAGUA,TALCA,CHILLÁN,CONCEPCIÓN,TEMUCO,VALDIVIA,PUERTO MONTT,COYHAIQUE,PUNTA ARENAS
9,NaN,1994-01-01 00:00:00,166.5,NaN,179.4,180.9,181.7,179.6,174.8,173.1,175.3,NaN,175.2,180.4,NaN,183.6,194.1,185.8

In [ ]:
df_93 = pd.read_excel(
    '../data/raw/precios_comb_liquidos_en_el_pais-2026-08-03.xlsx',
    sheet_name='Gasolina 93 sp',
    header=9
)
df_93.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,Fecha,METROPOLITANA,ARICA,IQUIQUE,ANTOFAGASTA,COPIAPÓ,LA SERENA,VALPARAÍSO,RANCAGUA,TALCA,CHILLÁN,CONCEPCIÓN,TEMUCO,VALDIVIA,PUERTO MONTT,COYHAIQUE,PUNTA ARENAS
1,NaN,1994-01-01 00:00:00,166.5,NaN,179.4,180.9,181.7,179.6,174.8,173.1,175.3,NaN,175.2,180.4,NaN,183.6,194.1,185.8
2,NaN,1994-02-01 00:00:00,166.3,NaN,179.6,ND,181.7,180.7,174.5,173.2,175.3,NaN,175.5,180.6,NaN,183.8,194.8,186.4
3,NaN,1994-03-01 00:00:00,166.3,NaN,179.6,181,181.7,179.8,174.7,173.2,175.3,NaN,175.6,180.8,NaN,183.8,195.1,184.1
4,NaN,1994-04-01 00:00:00,170.7,NaN,184.9,185.7,185.5,184.5,179.2,178.2,182.2,NaN,180.6,185.6,NaN,187.1,201.1,189.3